In [10]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/RPDR/Josh Lin/3_EHR_V2/CMS/Data/final_medicare.csv")

In [11]:
medicare = medicare[(medicare.Co_CAD_R0 == 1) | (medicare.Co_Diabetes_R0 == 1) | (medicare.Co_CAD_R0 == 1) | 
                    (medicare.Co_Embolism_R0 == 1) | (medicare.Co_DVT_R0 == 1) | (medicare.Co_PE_R0 == 1) | 
                    (medicare.Co_AFib_R0 == 1) | (medicare.Co_HF_R0 == 1) | (medicare.Co_HemoStroke_R0 == 1) | 
                    (medicare.Co_IscheStroke_R0 == 1) | (medicare.Co_OthStroke_R0 == 1) |(medicare.Co_TIA_R0 == 1)
                    | (medicare.Co_OldMI_R0 == 1) | (medicare.Co_AcuteMI_R0 == 1) | (medicare.Co_PVD_R0 == 1)]
medicare.shape

(52277, 281)

In [12]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH; n = 204014
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither; n = 115726
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]


In [13]:
medicare.head()

Unnamed: 0  Unnamed: 0.1  Out_comp_RC1  Out_comp_cardiovascular_RC1  \
0           0             0             0                            0   
1           1             1             0                            0   
2           2             2             0                            0   
3           3             3             0                            0   
4           4             4             0                            0   

   Unnamed: 0.1.1  Out_comp_cardiovascular_R1  Unnamed: 0.1.1.1  Co_CAD_R0  \
0               5                           0                 5        1.0   
1               6                           0                 6        0.0   
2              18                           0                18        0.0   
3              19                           0                19        1.0   
4              30                           0                30        1.0   

   Co_Embolism_R0  Co_DVT_R0  ...  Out_Hemorrhage_RC1  Hospital   D_Death_C  \
0             0.0        0.0  ...                 0.0       MGH         NaN   
1             0.0        0.0  ...                 0.0       MGH         NaN   
2             0.0        0.0  ...                 0.0       MGH         NaN   
3             0.0        0.0  ...                 0.0       MGH         NaN   
4             0.0        0.0  ...                 0.0       BWH  2016-02-15   

    D_Death_R  Co_Diabetes_R0  Co_Diabetes_RC0     D_Index  ehr_death  \
0         NaN             1.0              1.0  2011-09-30          0   
1         NaN             1.0              1.0  2012-12-30          0   
2         NaN             0.0              0.0  2013-12-31          0   
3         NaN             1.0              1.0  2016-09-29          0   
4  2016-02-15             0.0              1.0  2013-01-30          0   

   ehr_claims_death  claims_death  
0                 0             0  
1                 0             0  
2                 0             0  
3                 0             0  
4                 0             0  

[5 rows x 281 columns]

In [14]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]

co_train_gpop = train_set[predictor_variable]
co_train_high = train_set_high[predictor_variable]
co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_high = validation_set_high[predictor_variable]
co_validation_low = validation_set_low[predictor_variable]

In [15]:
out_train_death_gpop = train_set['Out_Hemorrhage_RC1']
out_train_death_high = train_set_high['Out_Hemorrhage_RC1']
out_train_death_low = train_set_low['Out_Hemorrhage_RC1']

out_validation_death_gpop = validation_set['Out_Hemorrhage_RC1']
out_validation_death_high = validation_set_high['Out_Hemorrhage_RC1']
out_validation_death_low = validation_set_low['Out_Hemorrhage_RC1']

In [16]:
"""
def a(b):
    count = 0
    tval = 0
    for val in b:
        tval = tval + 1
        if (val == 1):
            count = count + 1
    print(count, tval)
a(out_train_hemorrhage_gpop)
a(out_train_hemorrhage_high)
a(out_train_hemorrhage_low)
a(out_validation_hemorrhage_gpop)
a(out_validation_hemorrhage_high)
a(out_validation_hemorrhage_low)
"""


'\ndef a(b):\n    count = 0\n    tval = 0\n    for val in b:\n        tval = tval + 1\n        if (val == 1):\n            count = count + 1\n    print(count, tval)\na(out_train_hemorrhage_gpop)\na(out_train_hemorrhage_high)\na(out_train_hemorrhage_low)\na(out_validation_hemorrhage_gpop)\na(out_validation_hemorrhage_high)\na(out_validation_hemorrhage_low)\n'

# Template LR 

In [17]:
def lr(X_train, y_train):
    from sklearn.linear_model import Lasso
    from sklearn.decomposition import PCA
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import GridSearchCV
    from imblearn.over_sampling import SMOTE
    from sklearn.preprocessing import StandardScaler 

    model = LogisticRegression()
    param_grid = [
        {'C' : np.logspace(-4, 4, 20)}
        ]
    clf = GridSearchCV(model, param_grid, cv = 5, verbose = True, n_jobs = 10)
    best_clf = clf.fit(X_train, y_train)
    return best_clf

In [18]:
import pandas as pd
import numpy as np
import scipy.stats

# AUC comparison adapted from
# https://github.com/Netflix/vmaf/
def compute_midrank(x):
    """Computes midranks.
    Args:
       x - a 1D numpy array
    Returns:
       array of midranks
    """
    J = np.argsort(x)
    Z = x[J]
    N = len(x)
    T = np.zeros(N, dtype=np.float)
    i = 0
    while i < N:
        j = i
        while j < N and Z[j] == Z[i]:
            j += 1
        T[i:j] = 0.5*(i + j - 1)
        i = j
    T2 = np.empty(N, dtype=np.float)
    # Note(kazeevn) +1 is due to Python using 0-based indexing
    # instead of 1-based in the AUC formula in the paper
    T2[J] = T + 1
    return T2


def fastDeLong(predictions_sorted_transposed, label_1_count):
    """
    The fast version of DeLong's method for computing the covariance of
    unadjusted AUC.
    Args:
       predictions_sorted_transposed: a 2D numpy.array[n_classifiers, n_examples]
          sorted such as the examples with label "1" are first
    Returns:
       (AUC value, DeLong covariance)
    Reference:
     @article{sun2014fast,
       title={Fast Implementation of DeLong's Algorithm for
              Comparing the Areas Under Correlated Receiver Operating Characteristic Curves},
       author={Xu Sun and Weichao Xu},
       journal={IEEE Signal Processing Letters},
       volume={21},
       number={11},
       pages={1389--1393},
       year={2014},
       publisher={IEEE}
     }
    """
    # Short variables are named as they are in the paper
    m = label_1_count
    n = predictions_sorted_transposed.shape[1] - m
    positive_examples = predictions_sorted_transposed[:, :m]
    negative_examples = predictions_sorted_transposed[:, m:]
    k = predictions_sorted_transposed.shape[0]

    tx = np.empty([k, m], dtype=np.float)
    ty = np.empty([k, n], dtype=np.float)
    tz = np.empty([k, m + n], dtype=np.float)
    for r in range(k):
        tx[r, :] = compute_midrank(positive_examples[r, :])
        ty[r, :] = compute_midrank(negative_examples[r, :])
        tz[r, :] = compute_midrank(predictions_sorted_transposed[r, :])
    aucs = tz[:, :m].sum(axis=1) / m / n - float(m + 1.0) / 2.0 / n
    v01 = (tz[:, :m] - tx[:, :]) / n
    v10 = 1.0 - (tz[:, m:] - ty[:, :]) / m
    sx = np.cov(v01)
    sy = np.cov(v10)
    delongcov = sx / m + sy / n
    return aucs, delongcov


def calc_pvalue(aucs, sigma):
    """Computes log(10) of p-values.
    Args:
       aucs: 1D array of AUCs
       sigma: AUC DeLong covariances
    Returns:
       log10(pvalue)
    """
    l = np.array([[1, -1]])
    z = np.abs(np.diff(aucs)) / np.sqrt(np.dot(np.dot(l, sigma), l.T))
    return np.log10(2) + scipy.stats.norm.logsf(z, loc=0, scale=1) / np.log(10)


def compute_ground_truth_statistics(ground_truth):
    assert np.array_equal(np.unique(ground_truth), [0, 1])
    order = (-ground_truth).argsort()
    label_1_count = int(ground_truth.sum())
    return order, label_1_count


def delong_roc_variance(ground_truth, predictions):
    """
    Computes ROC AUC variance for a single set of predictions
    Args:
       ground_truth: np.array of 0 and 1
       predictions: np.array of floats of the probability of being class 1
    """
    order, label_1_count = compute_ground_truth_statistics(ground_truth)
    predictions_sorted_transposed = predictions[np.newaxis, order]
    aucs, delongcov = fastDeLong(predictions_sorted_transposed, label_1_count)
    assert len(aucs) == 1, "There is a bug in the code, please forward this to the developers"
    return aucs[0], delongcov


def delong_roc_test(ground_truth, predictions_one, predictions_two):
    """
    Computes log(p-value) for hypothesis that two ROC AUCs are different
    Args:
       ground_truth: np.array of 0 and 1
       predictions_one: predictions of the first model,
          np.array of floats of the probability of being class 1
       predictions_two: predictions of the second model,
          np.array of floats of the probability of being class 1
    """
    order, label_1_count = compute_ground_truth_statistics(ground_truth)
    predictions_sorted_transposed = np.vstack((predictions_one, predictions_two))[:, order]
    aucs, delongcov = fastDeLong(predictions_sorted_transposed, label_1_count)
    return calc_pvalue(aucs, delongcov)


In [19]:
def train_scores(X_train,y_train):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss

    pred = best_clf.predict(X_train)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict_proba(X_train)[:,1]))
    print(log_loss(actual,best_clf.predict_proba(X_train)[:,1]))
    
def test_scores(X_test,y_test):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss

    pred = best_clf.predict(X_test)
    actual = y_test
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict_proba(X_test)[:,1]))
    print(log_loss(actual,best_clf.predict_proba(X_test)[:,1]))
    


In [20]:
def cross_val(X,y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = [] 
    f1 = [] 
    f2 = [] 
    for train_index, test_index in cv.split(X):
        X_train, X_test, y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
        model = lr(X_train, y_train)
        prob = model.predict_proba(X_test)[:,1] # prob is a vector of probabilities 
        print(prob)
        pred = np.round(prob) # pred is the rounded predictions 
        
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))

In [21]:
from prince import FAMD
famd = FAMD(n_components = 15, n_iter = 3, random_state = 101)

for (colName, colData) in co_train_gpop.iteritems():
    if (colName != 'Co_N_Drugs_R0' and colName!= 'Co_N_Hosp_R0' and colName != 'Co_Total_HospLOS_R0' and colName != 'Co_N_MDVisit_R0'):
        co_train_gpop[colName].replace((1,0) ,('yes','no'), inplace = True)
        co_train_low[colName].replace((1,0) ,('yes','no'), inplace = True)
        co_train_high[colName].replace((1,0) ,('yes','no'), inplace = True)
        co_validation_gpop[colName].replace((1,0), ('yes','no'), inplace = True)
        co_validation_high[colName].replace((1,0), ('yes','no'), inplace = True)
        co_validation_low[colName].replace((1,0), ('yes','no'), inplace = True)




famd.fit(co_train_gpop)
co_train_gpop_FAMD = famd.transform(co_train_gpop)  

famd.fit(co_train_high)
co_train_high_FAMD = famd.transform(co_train_high)  

famd.fit(co_train_low)
co_train_low_FAMD = famd.transform(co_train_low)  

famd.fit(co_validation_gpop)
co_validation_gpop_FAMD = famd.transform(co_validation_gpop)    

famd.fit(co_validation_high)
co_validation_high_FAMD = famd.transform(co_validation_high)    

famd.fit(co_validation_low)
co_validation_low_FAMD = famd.transform(co_validation_low)    


/PHShome/se197/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4509: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


# General Population

In [22]:
best_clf = lr(co_train_gpop_FAMD, out_train_death_gpop)
cross_val(co_train_gpop_FAMD, out_train_death_gpop)
print()
test_scores(co_validation_gpop_FAMD, out_validation_death_gpop)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.07657898 0.06704413 0.09657858 ... 0.06042532 0.08049785 0.09766072]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.07934221 0.06489332 0.07250778 ... 0.06537448 0.06722199 0.0625809 ]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.04034628 0.28704364 0.04256742 ... 0.09228587 0.17155189 0.08603448]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.05555394 0.05467403 0.06607905 ... 0.1315553  0.16803672 0.08370647]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.06680267 0.05589619 0.05967698 ... 0.06305019 0.0578668  0.0685209 ]
0.9203313189625822
0.48113975239369616
0.4926529973974986
0.6696835252071913
0.267708827837179

0.9066613482249701
0.004255319148936169
0.4910896319771677
0.6227447032543822
0.302981612721497


['Co_CAD_R0[[0.24107423]]',
 'Co_Embolism_R0[[0.22404667]]',
 'Co_DVT_R0[[0.0143329]]',
 'Co_PE_R0[[-0.03831731]]',
 'Co_AFib_R0[[-0.27388231]]',
 'Co_Hypertension_R0[[0.15609647]]',
 'Co_Hyperlipidemia_R0[[-0.05034166]]',
 'Co_Atherosclerosis_R0[[-0.18926544]]',
 'Co_HF_R0[[0.19510579]]',
 'Co_HemoStroke_R0[[-0.45905881]]',
 'Co_IscheStroke_R0[[-0.05875006]]',
 'Co_OthStroke_R0[[0.37334012]]',
 'Co_TIA_R0[[0.00777675]]',
 'Co_COPD_R0[[-0.25287901]]',
 'Co_Asthma_R0[[0.2249851]]',
 'Co_Pneumonia_R0[]',
 'Co_Alcoholabuse_R0[]',
 'Co_Drugabuse_R0[]',
 'Co_Epilepsy_R0[]',
 'Co_Cancer_R0[]',
 'Co_MorbidObesity_R0[]',
 'Co_Dementia_R0[]',
 'Co_Depression_R0[]',
 'Co_Bipolar_R0[]',
 'Co_Psychosis_R0[]',
 'Co_Personalitydisorder_R0[]',
 'Co_Adjustmentdisorder_R0[]',
 'Co_Anxiety_R0[]',
 'Co_Generalizedanxiety_R0[]',
 'Co_OldMI_R0[]',
 'Co_AcuteMI_R0[]',
 'Co_PUD_R0[]',
 'Co_UpperGIbleed_R0[]',
 'Co_LowerGIbleed_R0[]',
 'Co_Urogenitalbleed_R0[]',
 'Co_Othbleed_R0[]',
 'Co_PVD_R0[]',
 'Co_Liver

# High Continuity 

In [23]:
best_clf = lr(co_train_high_FAMD, out_train_death_high)
cross_val(co_train_high_FAMD, out_train_death_high)
print()
test_scores(co_validation_high_FAMD, out_validation_death_high)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.06758254 0.06761964 0.06800342 ... 0.06818621 0.07154732 0.06700647]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.06701554 0.06539784 0.06544683 ... 0.06714634 0.06512303 0.06493084]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.05411382 0.06157638 0.03850872 ... 0.13413648 0.05334317 0.08607869]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.04603879 0.19102961 0.10287272 ... 0.06286436 0.05124803 0.13720318]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.05193186 0.04818795 0.04938497 ... 0.14065448 0.0675177  0.08739409]
0.9300290161555178
0.483549745737192
0.49360902413603236
0.6970394360072885
0.24391486334970888

0.9207558989350595
0.0
0.49153921612342266
0.6809580345227194
0.27350508906798376


['Co_CAD_R0[[0.07479085]]',
 'Co_Embolism_R0[[-0.00051536]]',
 'Co_DVT_R0[[-0.00148226]]',
 'Co_PE_R0[[-0.00034704]]',
 'Co_AFib_R0[[-0.00665563]]',
 'Co_Hypertension_R0[[0.00255559]]',
 'Co_Hyperlipidemia_R0[[0.00929165]]',
 'Co_Atherosclerosis_R0[[0.00221122]]',
 'Co_HF_R0[[-0.00326546]]',
 'Co_HemoStroke_R0[[-0.00620558]]',
 'Co_IscheStroke_R0[[-0.00232029]]',
 'Co_OthStroke_R0[[0.00888308]]',
 'Co_TIA_R0[[0.00117279]]',
 'Co_COPD_R0[[0.00028353]]',
 'Co_Asthma_R0[[-0.00630715]]',
 'Co_Pneumonia_R0[]',
 'Co_Alcoholabuse_R0[]',
 'Co_Drugabuse_R0[]',
 'Co_Epilepsy_R0[]',
 'Co_Cancer_R0[]',
 'Co_MorbidObesity_R0[]',
 'Co_Dementia_R0[]',
 'Co_Depression_R0[]',
 'Co_Bipolar_R0[]',
 'Co_Psychosis_R0[]',
 'Co_Personalitydisorder_R0[]',
 'Co_Adjustmentdisorder_R0[]',
 'Co_Anxiety_R0[]',
 'Co_Generalizedanxiety_R0[]',
 'Co_OldMI_R0[]',
 'Co_AcuteMI_R0[]',
 'Co_PUD_R0[]',
 'Co_UpperGIbleed_R0[]',
 'Co_LowerGIbleed_R0[]',
 'Co_Urogenitalbleed_R0[]',
 'Co_Othbleed_R0[]',
 'Co_PVD_R0[]',
 'Co_Li

# Low Continuity

In [24]:
best_clf = lr(co_train_low_FAMD, out_train_death_low)
cross_val(co_train_low_FAMD, out_train_death_low)
print()
test_scores(co_validation_low_FAMD, out_validation_death_low)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.08181551 0.0689639  0.03484998 ... 0.06131526 0.13267316 0.08620455]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.0904343  0.0860398  0.09025589 ... 0.09134718 0.09442702 0.09074155]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.08084145 0.14928249 0.0550079  ... 0.18042078 0.08398435 0.06601123]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.05757403 0.07275631 0.07145535 ... 0.37294241 0.07857633 0.11122812]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.12078312 0.08926163 0.08880335 ... 0.06088631 0.07621927 0.0893325 ]
0.9096202596278558
0.4763275156338905
0.4902519270940301
0.6273985837576253
0.2956859831435633

0.8937774384424508
0.0017937219730941704
0.48873973961295125
0.5965446069997997
0.33365054898613217


['Co_CAD_R0[[0.18266193]]',
 'Co_Embolism_R0[[-0.35506612]]',
 'Co_DVT_R0[[-0.16268899]]',
 'Co_PE_R0[[0.1950872]]',
 'Co_AFib_R0[[0.01947154]]',
 'Co_Hypertension_R0[[0.25869723]]',
 'Co_Hyperlipidemia_R0[[-0.01478839]]',
 'Co_Atherosclerosis_R0[[0.16584517]]',
 'Co_HF_R0[[-0.68226818]]',
 'Co_HemoStroke_R0[[0.53948069]]',
 'Co_IscheStroke_R0[[0.18626421]]',
 'Co_OthStroke_R0[[-0.01987841]]',
 'Co_TIA_R0[[-0.16972811]]',
 'Co_COPD_R0[[-0.00882964]]',
 'Co_Asthma_R0[[0.34693808]]',
 'Co_Pneumonia_R0[]',
 'Co_Alcoholabuse_R0[]',
 'Co_Drugabuse_R0[]',
 'Co_Epilepsy_R0[]',
 'Co_Cancer_R0[]',
 'Co_MorbidObesity_R0[]',
 'Co_Dementia_R0[]',
 'Co_Depression_R0[]',
 'Co_Bipolar_R0[]',
 'Co_Psychosis_R0[]',
 'Co_Personalitydisorder_R0[]',
 'Co_Adjustmentdisorder_R0[]',
 'Co_Anxiety_R0[]',
 'Co_Generalizedanxiety_R0[]',
 'Co_OldMI_R0[]',
 'Co_AcuteMI_R0[]',
 'Co_PUD_R0[]',
 'Co_UpperGIbleed_R0[]',
 'Co_LowerGIbleed_R0[]',
 'Co_Urogenitalbleed_R0[]',
 'Co_Othbleed_R0[]',
 'Co_PVD_R0[]',
 'Co_Live