In [1]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/data/CMS/Data/medicare.csv")

In [2]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither 
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

In [3]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Barbiturate_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]


co_train_gpop = train_set[predictor_variable]
co_train_high = train_set_high[predictor_variable]
co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_high = validation_set_high[predictor_variable]
co_validation_low = validation_set_low[predictor_variable]
len(predictor_variable)



126

In [4]:
out_train_comp_gpop = train_set['Out_comp_cardiovascular_nd_RC1']
out_train_comp_high = train_set_high['Out_comp_cardiovascular_nd_RC1']
out_train_comp_low = train_set_low['Out_comp_cardiovascular_nd_RC1']

out_validation_comp_gpop = validation_set['Out_comp_cardiovascular_nd_RC1']
out_validation_comp_high = validation_set_high['Out_comp_cardiovascular_nd_RC1']
out_validation_comp_low = validation_set_low['Out_comp_cardiovascular_nd_RC1']

In [5]:
def bart(X_train, y_train):
    from bartpy.sklearnmodel import SklearnModel
    from sklearn.model_selection import GridSearchCV
    from bartpy.data import Data
    from bartpy.sigma import Sigma
    param_grid = [{
        'n_trees': [10,30,50] #
    }]
    model = SklearnModel()
    clf = GridSearchCV(estimator = model, param_grid = param_grid, n_jobs = 10, verbose = True)
    best_clf = clf.fit(X_train, y_train.to_numpy())
    print(best_clf)
    return best_clf 

In [6]:
def scores(X_train,y_train, best_clf):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss
    import numpy as np
    pred = np.round(best_clf.predict(X_train))
    print(pred)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict(X_train)))
    print(log_loss(actual,best_clf.predict(X_train)))

In [7]:
def cross_val(X,y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = []
    f1 = []
    f2 = [] 
    for train_index, test_index in cv.split(X):
        X_train, X_test, y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
        model = bart(X_train, y_train)
        prob = model.predict(X_test) # prob is a vector of probabilities 
        pred = np.round(model.predict(X_test)) # pred is the rounded predictions 
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))

In [8]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_gpop_sm,out_train_comp_gpop_sm = sm.fit_resample(co_train_gpop,out_train_comp_gpop)

best_clf = bart(co_train_gpop_sm,out_train_comp_gpop_sm)

cross_val(co_train_gpop_sm,out_train_comp_gpop_sm)

print()

scores(co_train_gpop, out_train_comp_gpop, best_clf)

print() 

scores(co_validation_gpop,out_validation_comp_gpop, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-1.25738259         nan -0.68143476]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -0.78136962 -0.71402497]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-1.29423693         nan -0.71559865]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.92088758020526
0.6140248430229265
0.6137322896791162
0.9746372930422531
0.30859068769049186

[0. 0. 0. ... 0. 0. 0.]
0.9273455200024828
0.09016712009327635
0.5259742818486862
0.6362888351168989
0.3247580831332182

[0. 0. 0. ... 0. 0. 0.]
0.9193757479058636
0.08901408450704225
0.5245000459720984
0.6111281358259792
0.32653939688381656
2:21:46.514480


In [9]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_low_sm,out_train_comp_low_sm = sm.fit_resample(co_train_low,out_train_comp_low)

best_clf = bart(co_train_low_sm,out_train_comp_low_sm)

cross_val(co_train_low_sm,out_train_comp_low_sm)

print()

scores(co_train_low, out_train_comp_low, best_clf)

print() 

scores(co_validation_low,out_validation_comp_low, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -0.97801571 -0.91075227]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -1.00046732 -0.91341186]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-1.46174093         nan -0.97986101]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan -0.91108363]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -1.07454856 -0.96118622]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.8690180206537954
0.5790959921356603
0.5783725859082903
0.9519412575216869
0.3894661804692493

[0. 0. 0. ... 0. 0. 0.]
0.9142136248948697
0.11717709720372836
0.5355930407390196
0.6342765348787075
0.40680604821040134

[0. 0. 0. ... 0. 0. 0.]
0.9012216071769422
0.10078192875760209
0.5257067826455835
0.5850645137455379
0.41952106010941653
1:25:56.223638


In [8]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_high_sm,out_train_comp_high_sm = sm.fit_resample(co_train_high,out_train_comp_high)

best_clf = bart(co_train_high_sm,out_train_comp_high_sm)

cross_val(co_train_high_sm,out_train_comp_high_sm)

print()

scores(co_train_high, out_train_comp_high, best_clf)

print() 

scores(co_validation_high,out_validation_comp_high, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan -0.21825392]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan -0.28869053]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.99352662         nan -0.28156757]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -0.37262479 -0.25987757]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -0.3198241  -0.22451547]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.9691601661260346
0.7752312236720813
0.7750023665048438
0.9887297533531972
0.20253009953610085

[0. 0. 0. ... 0. 0. 0.]
0.9677284657599619
0.003683241252302026
0.49772328173574526
0.6839522304309293
0.22165820514537052

[0. 0. 0. ... 0. 0. 0.]
0.9685738149926916
0.0
0.4967444151727387
0.6398641948695839
0.2500152055650443
1:25:33.609316
