In [3]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/data/CMS/Data/medicare.csv")

In [4]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither 
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

In [5]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Barbiturate_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]


co_train_gpop = train_set[predictor_variable]
    
co_train_high = train_set_high[predictor_variable]

co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_gpop_split = np.array_split(co_validation_gpop, 5)  

co_validation_high = validation_set_high[predictor_variable]
co_validation_high_split = np.array_split(co_validation_high, 5)  

co_validation_low = validation_set_low[predictor_variable]
co_validation_low_split = np.array_split(co_validation_low, 5)  



In [6]:
out_train_hemorrhage_gpop = train_set['Out_Hemorrhage_RC1']

out_train_hemorrhage_high = train_set_high['Out_Hemorrhage_RC1']
out_train_hemorrhage_low = train_set_low['Out_Hemorrhage_RC1']

out_validation_hemorrhage_gpop_split = [] 
out_validation_hemorrhage_gpop = validation_set['Out_Hemorrhage_RC1']
for parts in co_validation_gpop_split:
    out_validation_hemorrhage_gpop_split.append(out_validation_hemorrhage_gpop[parts.index])

out_validation_hemorrhage_high_split = [] 
out_validation_hemorrhage_high = validation_set_high['Out_Hemorrhage_RC1']
for parts in co_validation_high_split:
    out_validation_hemorrhage_high_split.append(out_validation_hemorrhage_high[parts.index])

out_validation_hemorrhage_low_split = [] 
out_validation_hemorrhage_low = validation_set_low['Out_Hemorrhage_RC1']
for parts in co_validation_low_split:
    out_validation_hemorrhage_low_split.append(out_validation_hemorrhage_low[parts.index])

In [7]:
def bart(X_train, y_train):
    from bartpy.sklearnmodel import SklearnModel
    from sklearn.model_selection import GridSearchCV
    from bartpy.data import Data
    from bartpy.sigma import Sigma
    param_grid = [{
        'n_trees': [10,30,50] #
    }]
    model = SklearnModel()
    clf = GridSearchCV(estimator = model, param_grid = param_grid, n_jobs = 10, verbose = True)
    best_clf = clf.fit(X_train, y_train.to_numpy())
    print(best_clf)
    return best_clf 

In [8]:
def scores(X_train,y_train, best_clf):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss
    import numpy as np
    pred = np.round(best_clf.predict(X_train))
    print(pred)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict(X_train)))
    print(log_loss(actual,best_clf.predict(X_train)))

In [9]:
def cross_val(X,y,Or_X, Or_y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = [] 
    f1 = [] 
    f2 = [] 
    iter = 0
    for train_index, test_index in cv.split(X):
        
        X_train, X_test, y_train, y_test = X.iloc[train_index], Or_X[iter], y.iloc[train_index], Or_y[iter]
        model = bart(X_train, y_train)
        prob = model.predict(X_test) # prob is a vector of probabilities 
        print(prob)
        pred = np.round(prob) # pred is the rounded predictions 
        
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))
#co_train_gpop_sm,out_train_hemorrhage_gpop_sm, co_validation_gpop_split, out_validation_hemorrhage_gpop_split

In [10]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_gpop_sm,out_train_hemorrhage_gpop_sm = sm.fit_resample(co_train_gpop,out_train_hemorrhage_gpop)

best_clf = bart(co_train_gpop_sm,out_train_hemorrhage_gpop_sm)

cross_val(co_train_gpop_sm,out_train_hemorrhage_gpop_sm, co_validation_gpop_split, out_validation_hemorrhage_gpop_split)


Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.35022834 0.16855382 0.09908652 ... 0.30713337 0.41454542 0.11526653]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.61975355 -0.33744647         nan]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.39943577 0.1308774  0.12904063 ... 0.33134493 0.54799509 0.21602167]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [nan nan nan]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.25264177 0.21299934 0.21201205 ... 0.34237862 0.61188283 0.24240416]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.60754477         nan -0.29783058]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.30969051 0.14943787 0.09139363 ... 0.3066904  0.41646155 0.16077452]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.62039452         nan         nan]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.204382   0.20882877 0.1369749  ... 0.42025799 0.67961767 0.30354735]
0.8730807577268195
0.5195168284572376
0.520560068358079
0.5944509024365623
0.43695570850818155


In [11]:
scores(co_train_gpop, out_train_hemorrhage_gpop, best_clf)

print() 

scores(co_validation_gpop,out_validation_hemorrhage_gpop, best_clf)

[0. 0. 0. ... 0. 0. 0.]
0.896868501908693
0.08482511704764528
0.5137692096282568
0.6254725432977962
0.38133085161679414

[0. 0. 0. ... 0. 0. 0.]
0.8759972078181093
0.05973534971644614
0.49904039747840406
0.6051537981541746
0.4195684415015889


In [12]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_low_sm,out_train_hemorrhage_low_sm = sm.fit_resample(co_train_low,out_train_hemorrhage_low)

best_clf = bart(co_train_low_sm,out_train_hemorrhage_low_sm)

cross_val(co_train_low_sm,out_train_hemorrhage_low_sm, co_validation_low_split, out_validation_hemorrhage_low_split)

print()

scores(co_train_low, out_train_hemorrhage_low, best_clf)

print() 

scores(co_validation_low,out_validation_hemorrhage_low, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.76917886         nan -0.48218488]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.71097761         nan -0.51824479]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.39211955 0.14146744 0.3577907  ... 0.45563042 0.49765688 0.46935385]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.76970698         nan -0.51598881]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.36909412 0.18053605 0.37285503 ... 0.46265246 0.4798681  0.45640706]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan -0.5647341  -0.47783216]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.39585928 0.11726405 0.33779802 ... 0.36214554 0.49789406 0.48439195]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan -0.48020787]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.39727578 0.21580207 0.39258675 ... 0.41980546 0.49328838 0.49328838]
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.35798228 0.2116762  0.36877922 ... 0.49049895 0.48622631 0.47963751]
0.8930343511450383
0.5170569634257098
0.5155067541997536
0.5550510027736596
0.4962923822005603

[0. 0. 0. ... 0. 0. 0.]
0.893446334993854
0.09950792782941498
0.5190577993372264
0.5890300389678756
0.4607894759625051

[0. 0. 0. ... 0. 0. 0.]
0.8807978621874404
0.06301575393848462
0.5036970680455728
0.5531548203114088
0.5044936032344022
1:06:18.609041


In [13]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_high_sm,out_train_hemorrhage_high_sm = sm.fit_resample(co_train_high,out_train_hemorrhage_high)

best_clf = bart(co_train_high_sm,out_train_hemorrhage_high_sm)

cross_val(co_train_high_sm,out_train_hemorrhage_high_sm, co_validation_high_split, out_validation_hemorrhage_high_split)

print()

scores(co_train_high, out_train_hemorrhage_high, best_clf)

print() 

scores(co_validation_high,out_validation_hemorrhage_high, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan -0.0196971]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.29786214         nan -0.02249066]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.21823289 0.13930151 0.07281078 ... 0.35729088 0.21902485 0.20323673]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.31914086         nan -0.02876251]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.20432044 0.07802958 0.07323281 ... 0.18764687 0.33860091 0.23272165]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.32983716 -0.06666425         nan]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.21734481 0.10861898 0.05407083 ... 0.25315588 0.26131366 0.17024567]
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.20962406 0.04085592 0.18046919 ... 0.26686936 0.34198848 0.31549607]
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.28588325         nan -0.01389943]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
[0.28303401 0.0659916  0.1722433  ... 0.245655   0.30489621 0.23718951]
0.9195198329853863
0.4840117243746584
0.49399671169527853
0.6769014877211413
0.3172219272623872

[0. 0. 0. ... 0. 0. 0.]
0.928716296826533
0.04780876494023904
0.5071644393960187
0.7172051191577015
0.28550219886028444

[ 0. -0.  0. ...  0.  0.  0.]
0.9197118396324911
0.030264817150063048
0.5004569490411883
0.6875740350402272
0.3173539733236802
1:37:52.036970
