In [11]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/RPDR/Josh Lin/3_EHR_V2/CMS/Data/final_medicare.csv")

In [12]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither 
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]


In [13]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Barbiturate_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]

co_train_gpop = train_set[predictor_variable]
co_train_high = train_set_high[predictor_variable]
co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_high = validation_set_high[predictor_variable]
co_validation_low = validation_set_low[predictor_variable]

In [14]:
out_train_death_gpop = train_set['ehr_claims_death']
out_train_death_high = train_set_high['ehr_claims_death']
out_train_death_low = train_set_low['ehr_claims_death']

out_validation_death_gpop = validation_set['ehr_claims_death']
out_validation_death_high = validation_set_high['ehr_claims_death']
out_validation_death_low = validation_set_low['ehr_claims_death']

In [15]:
def lr(X_train, y_train):
    from sklearn.linear_model import Lasso
    from sklearn.decomposition import PCA
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import GridSearchCV
    from imblearn.over_sampling import SMOTE
    from sklearn.preprocessing import StandardScaler 

    model = LogisticRegression()
    param_grid = [
        {'C' : np.logspace(-4, 4, 20)}
        ]
    clf = GridSearchCV(model, param_grid, cv = 5, verbose = True, n_jobs = -1)
    best_clf = clf.fit(X_train, y_train)
    return best_clf

In [19]:
def scores(X_train,y_train):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss

    pred = best_clf.predict(X_train)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict_proba(X_train)[:,1]))
    print(log_loss(actual,best_clf.predict_proba(X_train)[:,1]))
    
    


In [20]:
def cross_val(X,y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = [] 
    f1 = [] 
    f2 = [] 
    for train_index, test_index in cv.split(X):
        X_train, X_test, y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
        model = lr(X_train, y_train)
        prob = model.predict_proba(X_test)[:,1] # prob is a vector of probabilities 
        print(prob)
        pred = np.round(prob) # pred is the rounded predictions 
        
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))

# General Population

In [21]:
best_clf = lr(co_train_gpop, out_train_death_gpop)
cross_val(co_train_gpop, out_train_death_gpop)
print()
scores(co_validation_gpop, out_validation_death_gpop)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.01893006 0.04767977 0.05671413 ... 0.01272838 0.09375855 0.2185393 ]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.04326576 0.05123501 0.05455705 ... 0.05081981 0.07516337 0.04738085]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.03190207 0.28291555 0.02367052 ... 0.10362224 0.06275244 0.10874595]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.03777999 0.04564137 0.06170606 ... 0.26452552 0.19907741 0.07596859]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.05050396 0.06255875 0.0544583  ... 0.04879479 0.0487402  0.06710783]
0.9220072725381506
0.4983172411639156
0.503327153482821
0.8050431418202768
0.23451786756165335

0.9093538093338652
0.00980392156862745
0.49289010124918825
0.7968309337166525
0.26069843546685256


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


['Co_CAD_R0[[0.01793722]]',
 'Co_Embolism_R0[[0.00887812]]',
 'Co_DVT_R0[[-0.00221457]]',
 'Co_PE_R0[[0.04002348]]',
 'Co_AFib_R0[[0.1215958]]',
 'Co_Hypertension_R0[[-0.04499079]]',
 'Co_Hyperlipidemia_R0[[-0.27690501]]',
 'Co_Atherosclerosis_R0[[0.00309533]]',
 'Co_HF_R0[[0.31078267]]',
 'Co_HemoStroke_R0[[0.09841217]]',
 'Co_IscheStroke_R0[[0.07291969]]',
 'Co_OthStroke_R0[[0.00165162]]',
 'Co_TIA_R0[[-0.03186338]]',
 'Co_COPD_R0[[0.2047862]]',
 'Co_Asthma_R0[[-0.08397421]]',
 'Co_Pneumonia_R0[[0.21742233]]',
 'Co_Alcoholabuse_R0[[-0.01387414]]',
 'Co_Drugabuse_R0[[-0.02571818]]',
 'Co_Epilepsy_R0[[0.02456001]]',
 'Co_Cancer_R0[[0.24190227]]',
 'Co_MorbidObesity_R0[[-0.03913938]]',
 'Co_Dementia_R0[[0.32862473]]',
 'Co_Depression_R0[[-0.01982456]]',
 'Co_Bipolar_R0[[-0.01282919]]',
 'Co_Psychosis_R0[[-0.00321116]]',
 'Co_Personalitydisorder_R0[[0.00265414]]',
 'Co_Adjustmentdisorder_R0[[-0.00165194]]',
 'Co_Anxiety_R0[[-0.04440339]]',
 'Co_Generalizedanxiety_R0[[-0.02198153]]',
 'Co

# Low Continuity 

In [22]:
best_clf = lr(co_train_low, out_train_death_low)
cross_val(co_train_low, out_train_death_low)
print()
scores(co_validation_low, out_validation_death_low)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.03340794 0.03757294 0.01416482 ... 0.00998087 0.12991849 0.05475247]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.03022916 0.00884703 0.04701851 ... 0.1653015  0.16641978 0.06669454]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.0482162  0.07899639 0.02044642 ... 0.49551186 0.05846426 0.02140484]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.0229493  0.0382701  0.02973874 ... 0.4046491  0.04034656 0.11071745]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.02433474 0.06156974 0.05388925 ... 0.05118364 0.03512442 0.07073953]
0.9033444967926328
0.5606173212365153
0.548082491863089
0.8019805338440179
0.26393969957335306

0.8842336323725902
0.11781818181818182
0.5250010620380992
0.7728749861783368
0.3062461464877448


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


['Co_CAD_R0[[0.07873636]]',
 'Co_Embolism_R0[[0.09496348]]',
 'Co_DVT_R0[[0.02984222]]',
 'Co_PE_R0[[0.21310593]]',
 'Co_AFib_R0[[0.13096936]]',
 'Co_Hypertension_R0[[-0.07827783]]',
 'Co_Hyperlipidemia_R0[[-0.2995357]]',
 'Co_Atherosclerosis_R0[[0.0390664]]',
 'Co_HF_R0[[0.55404513]]',
 'Co_HemoStroke_R0[[0.51274084]]',
 'Co_IscheStroke_R0[[0.30346691]]',
 'Co_OthStroke_R0[[-0.00693889]]',
 'Co_TIA_R0[[-0.30775632]]',
 'Co_COPD_R0[[0.50895519]]',
 'Co_Asthma_R0[[-0.4638624]]',
 'Co_Pneumonia_R0[[0.40531313]]',
 'Co_Alcoholabuse_R0[[-0.21992196]]',
 'Co_Drugabuse_R0[[-0.09487636]]',
 'Co_Epilepsy_R0[[0.14560113]]',
 'Co_Cancer_R0[[0.56444792]]',
 'Co_MorbidObesity_R0[[-0.06699982]]',
 'Co_Dementia_R0[[0.80719249]]',
 'Co_Depression_R0[[-0.08853544]]',
 'Co_Bipolar_R0[[-0.09844638]]',
 'Co_Psychosis_R0[[-0.26039234]]',
 'Co_Personalitydisorder_R0[[0.03206489]]',
 'Co_Adjustmentdisorder_R0[[0.00369695]]',
 'Co_Anxiety_R0[[-0.21968592]]',
 'Co_Generalizedanxiety_R0[[-0.0996751]]',
 'Co_Ol

# High Continuity 

In [23]:
best_clf = lr(co_train_high, out_train_death_high)
cross_val(co_train_high, out_train_death_high)
print()
scores(co_validation_high, out_validation_death_high)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.0285229  0.02037712 0.06025403 ... 0.03646388 0.04511247 0.03554111]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.04606496 0.04664287 0.01511115 ... 0.0222171  0.02432457 0.02350248]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.03566423 0.04304252 0.01789105 ... 0.07182119 0.03251828 0.1047765 ]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.03002233 0.18965616 0.05707624 ... 0.04581831 0.01931442 0.08300061]
Fitting 5 folds for each of 20 candidates, totalling 100 fits
[0.02943552 0.03056544 0.03468694 ... 0.08573022 0.05322787 0.10805642]
0.94076563430889
0.500437859495639
0.5034470444256872
0.8147979971515626
0.19074225857960037

0.9378784714971811
0.035656401944894646
0.5044372697958261
0.8065131859898185
0.1966819579587277


['Co_CAD_R0[[-0.08201748]]',
 'Co_Embolism_R0[[0.00390528]]',
 'Co_DVT_R0[[-0.00260652]]',
 'Co_PE_R0[[0.07814017]]',
 'Co_AFib_R0[[0.15093642]]',
 'Co_Hypertension_R0[[-0.09015526]]',
 'Co_Hyperlipidemia_R0[[-0.34853429]]',
 'Co_Atherosclerosis_R0[[0.07320143]]',
 'Co_HF_R0[[0.38968054]]',
 'Co_HemoStroke_R0[[0.01027615]]',
 'Co_IscheStroke_R0[[0.01348433]]',
 'Co_OthStroke_R0[[-0.0208462]]',
 'Co_TIA_R0[[0.05058966]]',
 'Co_COPD_R0[[0.27153641]]',
 'Co_Asthma_R0[[-0.21498557]]',
 'Co_Pneumonia_R0[[0.2279648]]',
 'Co_Alcoholabuse_R0[[-0.01636209]]',
 'Co_Drugabuse_R0[[-0.10034725]]',
 'Co_Epilepsy_R0[[-0.0388803]]',
 'Co_Cancer_R0[[0.45983666]]',
 'Co_MorbidObesity_R0[[-0.1184139]]',
 'Co_Dementia_R0[[0.45783825]]',
 'Co_Depression_R0[[-0.04055626]]',
 'Co_Bipolar_R0[[-0.05632492]]',
 'Co_Psychosis_R0[[-0.04094915]]',
 'Co_Personalitydisorder_R0[[0.00516582]]',
 'Co_Adjustmentdisorder_R0[[-0.01674102]]',
 'Co_Anxiety_R0[[-0.08146335]]',
 'Co_Generalizedanxiety_R0[[-0.08560719]]',
 'Co