In [3]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/RPDR/Josh Lin/3_EHR_V2/CMS/Data/final_medicare.csv")

In [41]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH; n = 204014
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither; n = 115726
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]


In [42]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]

co_train_gpop = train_set[predictor_variable]
    
co_train_high = train_set_high[predictor_variable]

co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_gpop_split = np.array_split(co_validation_gpop, 5)  

co_validation_high = validation_set_high[predictor_variable]
co_validation_high_split = np.array_split(co_validation_high, 5)  

co_validation_low = validation_set_low[predictor_variable]
co_validation_low_split = np.array_split(co_validation_low, 5)  


4012


In [43]:
out_train_death_gpop = train_set['ehr_claims_death']

out_train_death_high = train_set_high['ehr_claims_death']
out_train_death_low = train_set_low['ehr_claims_death']

out_validation_death_gpop_split = [] 
out_validation_death_gpop = validation_set['ehr_claims_death']
for parts in co_validation_gpop_split:
    out_validation_death_gpop_split.append(out_validation_death_gpop[parts.index])
print(len(out_validation_death_gpop_split[0]))

out_validation_death_high_split = []
out_validation_death_high = validation_set_high['ehr_claims_death']
for parts in co_validation_high_split:
    print()
    out_validation_death_high_split.append(out_validation_death_high[parts.index])
#print(out_validation_death_high_split[0])
out_validation_death_low_split = []
out_validation_death_low = validation_set_low['ehr_claims_death']
for parts in co_validation_low_split:
    out_validation_death_low_split.append(out_validation_death_low[parts.index])

4012







In [44]:
def lr(X_train, y_train):
    from sklearn.linear_model import Lasso
    from sklearn.decomposition import PCA
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import GridSearchCV
    from imblearn.over_sampling import SMOTE
    from sklearn.preprocessing import StandardScaler 

    model = LogisticRegression()
    param_grid = [
        {'C' : np.logspace(-4, 4, 20)}
        ]
    clf = GridSearchCV(model, param_grid, cv = 5, verbose = True, n_jobs = -1)
    best_clf = clf.fit(X_train, y_train)
    return best_clf

In [45]:
def scores(X_train,y_train):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss

    pred = best_clf.predict(X_train)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict_proba(X_train)[:,1]))
    print(log_loss(actual,best_clf.predict_proba(X_train)[:,1]))
    
    


In [46]:
def cross_val(X,y,Or_X, Or_y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = [] 
    f1 = [] 
    f2 = [] 
    print(cv.split(X))
    iter = 0
    for train_index, test_index in cv.split(X):
        
        X_train, X_test, y_train, y_test = X.iloc[train_index], Or_X[iter], y.iloc[train_index], Or_y[iter]
        model = lr(X_train, y_train)
        prob = model.predict_proba(X_test)[:,1] # prob is a vector of probabilities 
        print(prob)
        pred = np.round(prob) # pred is the rounded predictions 
        
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))

# General Population 

In [47]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_gpop_sm,out_train_death_gpop_sm = sm.fit_resample(co_train_gpop,out_train_death_gpop)

best_clf = lr(co_train_gpop_sm, out_train_death_gpop_sm)

cross_val(co_train_gpop_sm, out_train_death_gpop_sm, co_validation_gpop_split, out_validation_death_gpop_split)

print()

scores(co_train_gpop, out_train_death_gpop)

print()

scores(co_validation_gpop, out_validation_death_gpop)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


<generator object _BaseKFold.split at 0x7f2fa0853b30>
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.43206481 0.21797313 0.19950953 ... 0.63843233 0.65522106 0.40518759]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.42016056 0.23054226 0.19163699 ... 0.63657236 0.68268391 0.43477156]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.43605655 0.23122203 0.19531898 ... 0.62481107 0.64691016 0.37601543]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.38616545 0.21281909 0.18710002 ... 0.65025873 0.64735861 0.37917046]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.48626957 0.19819598 0.19547656 ... 0.65390788 0.65579715 0.39325942]
0.7415752741774677
0.5934733006767731
0.6427191139362458
0.8008278025736146
0.5808241935388894

0.7726327550355359
0.37234407128169983
0.6668235410054781
0.8232139937794526
0.5214141860634781

0.7245213402473075
0.34992352041416636
0.6336328100743743
0.7910405293941463
0.5997223354166593


['Co_CAD_R0[[0.14237405]]',
 'Co_Embolism_R0[[0.09668354]]',
 'Co_DVT_R0[[-0.20214606]]',
 'Co_PE_R0[[0.17017016]]',
 'Co_AFib_R0[[0.34470762]]',
 'Co_Hypertension_R0[[-0.11448948]]',
 'Co_Hyperlipidemia_R0[[-0.60299526]]',
 'Co_Atherosclerosis_R0[[0.03818935]]',
 'Co_HF_R0[[0.63917681]]',
 'Co_HemoStroke_R0[[0.37826402]]',
 'Co_IscheStroke_R0[[0.03083912]]',
 'Co_OthStroke_R0[[-0.10826909]]',
 'Co_TIA_R0[[-0.40075244]]',
 'Co_COPD_R0[[0.63282166]]',
 'Co_Asthma_R0[[-0.76946601]]',
 'Co_Pneumonia_R0[[0.41494503]]',
 'Co_Alcoholabuse_R0[[-0.4001381]]',
 'Co_Drugabuse_R0[[-0.33662067]]',
 'Co_Epilepsy_R0[[-0.08956885]]',
 'Co_Cancer_R0[[0.64143706]]',
 'Co_MorbidObesity_R0[[-0.259645]]',
 'Co_Dementia_R0[[1.19686811]]',
 'Co_Depression_R0[[-0.22095081]]',
 'Co_Bipolar_R0[[-0.24481832]]',
 'Co_Psychosis_R0[[-0.33355743]]',
 'Co_Personalitydisorder_R0[[0.01383259]]',
 'Co_Adjustmentdisorder_R0[[-0.04660632]]',
 'Co_Anxiety_R0[[-0.29753508]]',
 'Co_Generalizedanxiety_R0[[-0.08723289]]',
 'C

# High Continuity

In [48]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_high_sm,out_train_death_high_sm = sm.fit_resample(co_train_high,out_train_death_high)

best_clf = lr(co_train_high_sm, out_train_death_high_sm)

cross_val(co_train_high_sm, out_train_death_high_sm, co_validation_high_split, out_validation_death_high_split)

print()

scores(co_train_high, out_train_death_high)

print()

scores(co_validation_high, out_validation_death_high)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


<generator object _BaseKFold.split at 0x7f2fa08574a0>
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.18639324 0.30158073 0.12760649 ... 0.36060721 0.93190497 0.7084054 ]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.20596051 0.26038571 0.16895168 ... 0.49778219 0.93299875 0.70616531]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.17051056 0.31427288 0.16278918 ... 0.46379546 0.93096292 0.65516933]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.17232192 0.30119062 0.10870268 ... 0.42750316 0.93653197 0.67378961]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.1770939  0.32191979 0.14111003 ... 0.40629021 0.9426585  0.71361602]
0.7613778705636743
0.5817807777049782
0.6343014240387111
0.8143243243243242
0.5263136857636991

0.7808995466475781
0.3239462543714338
0.6547707347594924
0.8506980149817308
0.4877634964007227

0.7510962622676968
0.28149487643158533
0.6146381012047788
0.806288615815097
0.5336081282672017


['Co_CAD_R0[[-0.0728388]]',
 'Co_Embolism_R0[[-0.08262925]]',
 'Co_DVT_R0[[-0.11118969]]',
 'Co_PE_R0[[0.01966909]]',
 'Co_AFib_R0[[0.18637906]]',
 'Co_Hypertension_R0[[-0.05061673]]',
 'Co_Hyperlipidemia_R0[[-0.60308967]]',
 'Co_Atherosclerosis_R0[[0.04792115]]',
 'Co_HF_R0[[0.73694057]]',
 'Co_HemoStroke_R0[[-0.14337673]]',
 'Co_IscheStroke_R0[[-0.12881967]]',
 'Co_OthStroke_R0[[-0.29719309]]',
 'Co_TIA_R0[[0.1542318]]',
 'Co_COPD_R0[[0.54413189]]',
 'Co_Asthma_R0[[-0.77216098]]',
 'Co_Pneumonia_R0[[0.28675089]]',
 'Co_Alcoholabuse_R0[[-0.23744109]]',
 'Co_Drugabuse_R0[[-0.43973192]]',
 'Co_Epilepsy_R0[[-0.16160867]]',
 'Co_Cancer_R0[[0.83495389]]',
 'Co_MorbidObesity_R0[[-0.33305993]]',
 'Co_Dementia_R0[[0.97598979]]',
 'Co_Depression_R0[[-0.11380729]]',
 'Co_Bipolar_R0[[-0.27533752]]',
 'Co_Psychosis_R0[[-0.31227704]]',
 'Co_Personalitydisorder_R0[[0.08125114]]',
 'Co_Adjustmentdisorder_R0[[-0.00428972]]',
 'Co_Anxiety_R0[[-0.18529936]]',
 'Co_Generalizedanxiety_R0[[-0.10152721]]',

# Low Continuity

In [49]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_low_sm,out_train_death_low_sm = sm.fit_resample(co_train_low,out_train_death_low)

best_clf = lr(co_train_low_sm, out_train_death_low_sm)

cross_val(co_train_low_sm, out_train_death_low_sm, co_validation_low_split, out_validation_death_low_split)

print()

scores(co_train_low, out_train_death_low)

print()

scores(co_validation_low, out_validation_death_low)

comb = [] 
for i in range(len(predictor_variable)):
    comb.append(predictor_variable[i] + str(best_clf.best_estimator_.coef_[:,i:i+1]))
comb

Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


<generator object _BaseKFold.split at 0x7f2fa09fa900>
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.28053629 0.14109334 0.36716451 ... 0.59912302 0.46680965 0.37303094]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.27036398 0.13971633 0.3892721  ... 0.55578412 0.44979585 0.36240077]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.2588017  0.13217435 0.40992498 ... 0.54805495 0.45099202 0.35480658]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.2906993  0.14605157 0.37721452 ... 0.58809912 0.45514434 0.36742304]
Fitting 5 folds for each of 20 candidates, totalling 100 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.24165139 0.14962855 0.36046051 ... 0.57511345 0.44992708 0.36183133]
0.7248091603053435
0.6016092017034663
0.6427356081097304
0.7753318209413044
0.6053885911559064

0.7746652002329042
0.4292970670162215
0.6866051662485904
0.8113278520211631
0.526311509213785

0.7141630082076732
0.3928643827285627
0.6411710567119914
0.7663214621190227
0.6115311115235376


['Co_CAD_R0[[0.05280799]]',
 'Co_Embolism_R0[[0.28390082]]',
 'Co_DVT_R0[[-0.23269932]]',
 'Co_PE_R0[[0.43796427]]',
 'Co_AFib_R0[[0.28316225]]',
 'Co_Hypertension_R0[[-0.04507299]]',
 'Co_Hyperlipidemia_R0[[-0.56835623]]',
 'Co_Atherosclerosis_R0[[0.08845226]]',
 'Co_HF_R0[[0.66645881]]',
 'Co_HemoStroke_R0[[0.64714299]]',
 'Co_IscheStroke_R0[[0.27690419]]',
 'Co_OthStroke_R0[[0.09896894]]',
 'Co_TIA_R0[[-0.73916395]]',
 'Co_COPD_R0[[0.57887166]]',
 'Co_Asthma_R0[[-0.42153891]]',
 'Co_Pneumonia_R0[[0.44007295]]',
 'Co_Alcoholabuse_R0[[-0.58216119]]',
 'Co_Drugabuse_R0[[-0.29377584]]',
 'Co_Epilepsy_R0[[-0.03824424]]',
 'Co_Cancer_R0[[0.72866027]]',
 'Co_MorbidObesity_R0[[0.10146437]]',
 'Co_Dementia_R0[[1.16534531]]',
 'Co_Depression_R0[[-0.3216846]]',
 'Co_Bipolar_R0[[-0.17755741]]',
 'Co_Psychosis_R0[[-0.48097074]]',
 'Co_Personalitydisorder_R0[[0.04213957]]',
 'Co_Adjustmentdisorder_R0[[-0.10416197]]',
 'Co_Anxiety_R0[[-0.24574676]]',
 'Co_Generalizedanxiety_R0[[-0.17911355]]',
 'C