In [1]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/data/CMS/Data/medicare.csv")

In [2]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH; n = 204014
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither; n = 115726
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]


In [3]:
predictor_variable = [
        'Co_CAD_R0', 'Co_Embolism_R0', 'Co_DVT_R0', 'Co_PE_R0', 'Co_AFib_R0',
        'Co_Hypertension_R0', 'Co_Hyperlipidemia_R0', 'Co_Atherosclerosis_R0',
        'Co_HF_R0', 'Co_HemoStroke_R0', 'Co_IscheStroke_R0', 'Co_OthStroke_R0',
        'Co_TIA_R0', 'Co_COPD_R0', 'Co_Asthma_R0', 'Co_Pneumonia_R0', 'Co_Alcoholabuse_R0',
        'Co_Drugabuse_R0', 'Co_Epilepsy_R0', 'Co_Cancer_R0', 'Co_MorbidObesity_R0',
        'Co_Dementia_R0', 'Co_Depression_R0', 'Co_Bipolar_R0', 'Co_Psychosis_R0',
        'Co_Personalitydisorder_R0', 'Co_Adjustmentdisorder_R0', 'Co_Anxiety_R0',
        'Co_Generalizedanxiety_R0', 'Co_OldMI_R0', 'Co_AcuteMI_R0', 'Co_PUD_R0',
        'Co_UpperGIbleed_R0', 'Co_LowerGIbleed_R0', 'Co_Urogenitalbleed_R0',
        'Co_Othbleed_R0', 'Co_PVD_R0', 'Co_LiverDisease_R0', 'Co_MRI_R0',
        'Co_ESRD_R0', 'Co_Obesity_R0', 'Co_Sepsis_R0', 'Co_Osteoarthritis_R0',
        'Co_RA_R0', 'Co_NeuroPain_R0', 'Co_NeckPain_R0', 'Co_OthArthritis_R0',
        'Co_Osteoporosis_R0', 'Co_Fibromyalgia_R0', 'Co_Migraine_R0', 'Co_Headache_R0',
        'Co_OthPain_R0', 'Co_GeneralizedPain_R0', 'Co_PainDisorder_R0',
        'Co_Falls_R0', 'Co_CoagulationDisorder_R0', 'Co_WhiteBloodCell_R0', 'Co_Parkinson_R0',
        'Co_Anemia_R0', 'Co_UrinaryIncontinence_R0', 'Co_DecubitusUlcer_R0',
        'Co_Oxygen_R0', 'Co_Mammography_R0', 'Co_PapTest_R0', 'Co_PSATest_R0',
        'Co_Colonoscopy_R0', 'Co_FecalOccultTest_R0', 'Co_FluShot_R0', 'Co_PneumococcalVaccine_R0', 'Co_RenalDysfunction_R0', 'Co_Valvular_R0', 'Co_Hosp_Prior30Days_R0',
        'Co_RX_Antibiotic_R0', 'Co_RX_Corticosteroid_R0', 'Co_RX_Aspirin_R0', 'Co_RX_Dipyridamole_R0',
        'Co_RX_Clopidogrel_R0', 'Co_RX_Prasugrel_R0', 'Co_RX_Cilostazol_R0', 'Co_RX_Ticlopidine_R0',
        'Co_RX_Ticagrelor_R0', 'Co_RX_OthAntiplatelet_R0', 'Co_RX_NSAIDs_R0',
        'Co_RX_Opioid_R0', 'Co_RX_Antidepressant_R0', 'Co_RX_AAntipsychotic_R0', 'Co_RX_TAntipsychotic_R0',
        'Co_RX_Anticonvulsant_R0', 'Co_RX_PPI_R0', 'Co_RX_H2Receptor_R0', 'Co_RX_OthGastro_R0',
        'Co_RX_ACE_R0', 'Co_RX_ARB_R0', 'Co_RX_BBlocker_R0', 'Co_RX_CCB_R0', 'Co_RX_Thiazide_R0',
        'Co_RX_Loop_R0', 'Co_RX_Potassium_R0', 'Co_RX_Nitrates_R0', 'Co_RX_Aliskiren_R0',
        'Co_RX_OthAntihypertensive_R0', 'Co_RX_Antiarrhythmic_R0', 'Co_RX_OthAnticoagulant_R0',
        'Co_RX_Insulin_R0', 'Co_RX_Noninsulin_R0', 'Co_RX_Digoxin_R0', 'Co_RX_Statin_R0',
        'Co_RX_Lipid_R0', 'Co_RX_Lithium_R0', 'Co_RX_Benzo_R0', 'Co_RX_ZDrugs_R0',
        'Co_RX_OthAnxiolytic_R0', 'Co_RX_Barbiturate_R0', 'Co_RX_Dementia_R0', 'Co_RX_Hormone_R0',
        'Co_RX_Osteoporosis_R0', 'Co_N_Drugs_R0', 'Co_N_Hosp_R0', 'Co_Total_HospLOS_R0',
        'Co_N_MDVisit_R0', 'Co_RX_AnyAspirin_R0', 'Co_RX_AspirinMono_R0', 'Co_RX_ClopidogrelMono_R0',
        'Co_RX_AspirinClopidogrel_R0', 'Co_RX_DM_R0', 'Co_RX_Antipsychotic_R0'
]

co_train_gpop = train_set[predictor_variable]
    
co_train_high = train_set_high[predictor_variable]

co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_gpop_split = np.array_split(co_validation_gpop, 5)  

co_validation_high = validation_set_high[predictor_variable]
co_validation_high_split = np.array_split(co_validation_high, 5)  

co_validation_low = validation_set_low[predictor_variable]
co_validation_low_split = np.array_split(co_validation_low, 5)  


In [4]:
out_train_hemorrhage_gpop = train_set['Out_Hemorrhage_RC1']

out_train_hemorrhage_high = train_set_high['Out_Hemorrhage_RC1']
out_train_hemorrhage_low = train_set_low['Out_Hemorrhage_RC1']

out_validation_hemorrhage_gpop_split = [] 
out_validation_hemorrhage_gpop = validation_set['Out_Hemorrhage_RC1']
for parts in co_validation_gpop_split:
    out_validation_hemorrhage_gpop_split.append(out_validation_hemorrhage_gpop[parts.index])

out_validation_hemorrhage_high_split = [] 
out_validation_hemorrhage_high = validation_set_high['Out_Hemorrhage_RC1']
for parts in co_validation_high_split:
    out_validation_hemorrhage_high_split.append(out_validation_hemorrhage_high[parts.index])

out_validation_hemorrhage_low_split = [] 
out_validation_hemorrhage_low = validation_set_low['Out_Hemorrhage_RC1']
for parts in co_validation_low_split:
    out_validation_hemorrhage_low_split.append(out_validation_hemorrhage_low[parts.index])

In [5]:
def rf(X_train, y_train):
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import GridSearchCV

    param_grid = {'bootstrap': [True],
         'max_depth': [6, 10],
         'min_samples_leaf': [3, 5],
         'min_samples_split': [4, 6],
         'n_estimators': [100, 350]
        }


    forest_clf = RandomForestClassifier()

    forest_grid_search = GridSearchCV(forest_clf, param_grid, cv=5,
                                      scoring="accuracy",
                                      return_train_score=True,
                                      verbose=True,
                                      n_jobs=10)

    best_clf = forest_grid_search.fit(X_train, y_train)
    return best_clf 


In [6]:
def scores(X,y):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss

    pred = best_clf.predict(X)
    actual = y
    #file = open('hem_smote_rf_ehr.out', 'a')
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict_proba(X)[:,1]))
    print(log_loss(actual,best_clf.predict_proba(X)[:,1]))

In [10]:
def cross_val(X,y,Or_X, Or_y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = [] 
    f1 = [] 
    f2 = [] 
    iter = 0
    for train_index, test_index in cv.split(X):
        
        X_train, X_test, y_train, y_test = X.iloc[train_index], Or_X[iter], y.iloc[train_index], Or_y[iter]
        model = rf(X_train, y_train)
        prob = model.predict_proba(X_test)[:,1] # prob is a vector of probabilities 
        print(prob)
        pred = np.round(prob) # pred is the rounded predictions 
        
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))
#co_train_gpop_sm,out_train_hemorrhage_gpop_sm, co_validation_gpop_split, out_validation_hemorrhage_gpop_split

# General Population

In [11]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_gpop_sm,out_train_hemorrhage_gpop_sm = sm.fit_resample(co_train_gpop,out_train_hemorrhage_gpop)

best_clf = rf(co_train_gpop_sm, out_train_hemorrhage_gpop_sm)


Fitting 5 folds for each of 16 candidates, totalling 80 fits


In [12]:
cross_val(co_train_gpop_sm, out_train_hemorrhage_gpop_sm, co_validation_gpop_split, out_validation_hemorrhage_gpop_split)
#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_train_gpop, out_train_hemorrhage_gpop)
#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_validation_gpop, out_validation_hemorrhage_gpop)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.29220977 0.18380564 0.17256197 ... 0.33450388 0.46026403 0.28596844]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.30499179 0.16531811 0.17217911 ... 0.34952383 0.45080171 0.28479185]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.29159877 0.18807379 0.17673286 ... 0.35463727 0.44271672 0.28308242]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.27778633 0.19551642 0.17704743 ... 0.34557463 0.45002744 0.28098563]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.29524652 0.19031891 0.16791425 ... 0.38231499 0.44803648 0.27932956]
0.856679960119641
0.5071353183344932
0.507007601976889
0.6119119021337422
0.4160794013696513

0.8806368517426523
0.17503217503217502
0.552531566616522
0.7523024531688816
0.3809338394735238

0.8532110091743119
0.11164755582377792
0.515050815672789
0.6228177237177889
0.42384995386337443


# Low Continuity 

In [13]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_low_sm,out_train_hemorrhage_low_sm = sm.fit_resample(co_train_low,out_train_hemorrhage_low)

best_clf = rf(co_train_low_sm, out_train_hemorrhage_low_sm)

cross_val(co_train_low_sm, out_train_hemorrhage_low_sm, co_validation_low_split, out_validation_hemorrhage_low_split)
#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_train_low, out_train_hemorrhage_low)

#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_validation_low, out_validation_hemorrhage_low)



Fitting 5 folds for each of 16 candidates, totalling 80 fits
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.32495121 0.16042614 0.37256211 ... 0.4297048  0.55030043 0.5080647 ]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.36247433 0.1513747  0.38575819 ... 0.43966682 0.54044889 0.49910307]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.33804807 0.15841115 0.36971033 ... 0.39686478 0.52601026 0.49508424]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.32227469 0.14320652 0.38841652 ... 0.40076839 0.52859291 0.49460582]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.33394349 0.16545168 0.35579146 ... 0.40969591 0.52569734 0.4789893 ]
0.8439885496183207
0.5070682432457516
0.507371893772557
0.5474490043675856
0.4788920860711139

0.8632981820534386
0.19320351279114165
0.5572626539336857
0.7430816492565352
0.437694745115072

0.8394731819049437
0.12121212121212122
0.5155808685149678
0.5613547417087659
0.4824

# High Continuity

In [14]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_high_sm,out_train_hemorrhage_high_sm = sm.fit_resample(co_train_high,out_train_hemorrhage_high)

best_clf = rf(co_train_high_sm, out_train_hemorrhage_high_sm)

cross_val(co_train_high_sm, out_train_hemorrhage_high_sm, co_validation_high_split, out_validation_hemorrhage_high_split)
#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_train_high, out_train_hemorrhage_high)
#, file = open('hem_smote_rf_ehr.out', 'a')
print("")

scores(co_validation_high, out_validation_hemorrhage_high)


Fitting 5 folds for each of 16 candidates, totalling 80 fits
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.16611582 0.10144624 0.13581071 ... 0.22487158 0.32069961 0.20830339]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.20402837 0.10954813 0.11264117 ... 0.23100262 0.30147268 0.17425273]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.18874732 0.11961381 0.11612141 ... 0.2145962  0.32398177 0.23497526]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.18602895 0.11702076 0.11266999 ... 0.20476657 0.30668621 0.18179782]
Fitting 5 folds for each of 16 candidates, totalling 80 fits
[0.1658352  0.10726337 0.11677146 ... 0.20936004 0.34047752 0.19977819]
0.9184759916492693
0.48506267625652855
0.4943454072620536
0.7205237979100614
0.30704143649244553

0.9371271772846576
0.19541984732824427
0.5594237560410633
0.8956777313162342
0.25941353875436024

0.9187721862601795
0.029925187032418945
0.5000248273088714
0.7125152439912568
