In [8]:
import pandas as pd
medicare = pd.read_csv("/netapp2/home/se197/data/CMS/Data/medicare.csv")

In [9]:
train_set = medicare[medicare.Hospital != 'BWH'] # MGH
validation_set = medicare[medicare.Hospital == 'BWH'] # BWH and Neither 
import numpy as np

fifty_perc_EHR_cont = np.percentile(medicare['Cal_MPEC_R0'],50)
train_set_high = train_set[train_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
train_set_low= train_set[train_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

validation_set_high = validation_set[validation_set.Cal_MPEC_R0 >= fifty_perc_EHR_cont]
validation_set_low = validation_set[validation_set.Cal_MPEC_R0 < fifty_perc_EHR_cont]

In [10]:
predictor_variable = [
    'Co_CAD_RC0', 'Co_Embolism_RC0', 'Co_DVT_RC0', 'Co_PE_RC0', 'Co_AFib_RC0',
        'Co_Hypertension_RC0', 'Co_Hyperlipidemia_RC0', 'Co_Atherosclerosis_RC0',
        'Co_HF_RC0', 'Co_HemoStroke_RC0', 'Co_IscheStroke_RC0', 'Co_OthStroke_RC0',
        'Co_TIA_RC0', 'Co_COPD_RC0', 'Co_Asthma_RC0', 'Co_Pneumonia_RC0', 'Co_Alcoholabuse_RC0',
        'Co_Drugabuse_RC0', 'Co_Epilepsy_RC0', 'Co_Cancer_RC0', 'Co_MorbidObesity_RC0',
        'Co_Dementia_RC0', 'Co_Depression_RC0', 'Co_Bipolar_RC0', 'Co_Psychosis_RC0',
        'Co_Personalitydisorder_RC0', 'Co_Adjustmentdisorder_RC0', 'Co_Anxiety_RC0',
        'Co_Generalizedanxiety_RC0', 'Co_OldMI_RC0', 'Co_AcuteMI_RC0', 'Co_PUD_RC0',
        'Co_UpperGIbleed_RC0', 'Co_LowerGIbleed_RC0', 'Co_Urogenitalbleed_RC0',
        'Co_Othbleed_RC0', 'Co_PVD_RC0', 'Co_LiverDisease_RC0', 'Co_MRI_RC0',
        'Co_ESRD_RC0', 'Co_Obesity_RC0', 'Co_Sepsis_RC0', 'Co_Osteoarthritis_RC0',
        'Co_RA_RC0', 'Co_NeuroPain_RC0', 'Co_NeckPain_RC0', 'Co_OthArthritis_RC0',
        'Co_Osteoporosis_RC0', 'Co_Fibromyalgia_RC0', 'Co_Migraine_RC0', 'Co_Headache_RC0',
        'Co_OthPain_RC0', 'Co_GeneralizedPain_RC0', 'Co_PainDisorder_RC0',
        'Co_Falls_RC0', 'Co_CoagulationDisorder_RC0', 'Co_WhiteBloodCell_RC0', 'Co_Parkinson_RC0',
        'Co_Anemia_RC0', 'Co_UrinaryIncontinence_RC0', 'Co_DecubitusUlcer_RC0',
        'Co_Oxygen_RC0', 'Co_Mammography_RC0', 'Co_PapTest_RC0', 'Co_PSATest_RC0',
        'Co_Colonoscopy_RC0', 'Co_FecalOccultTest_RC0', 'Co_FluShot_RC0', 'Co_PneumococcalVaccine_RC0' , 'Co_RenalDysfunction_RC0', 'Co_Valvular_RC0', 'Co_Hosp_Prior30Days_RC0',
        'Co_RX_Antibiotic_RC0', 'Co_RX_Corticosteroid_RC0', 'Co_RX_Aspirin_RC0', 'Co_RX_Dipyridamole_RC0',
        'Co_RX_Clopidogrel_RC0', 'Co_RX_Prasugrel_RC0', 'Co_RX_Cilostazol_RC0', 'Co_RX_Ticlopidine_RC0',
        'Co_RX_Ticagrelor_RC0', 'Co_RX_OthAntiplatelet_RC0', 'Co_RX_NSAIDs_RC0',
        'Co_RX_Opioid_RC0', 'Co_RX_Antidepressant_RC0', 'Co_RX_AAntipsychotic_RC0', 'Co_RX_TAntipsychotic_RC0',
        'Co_RX_Anticonvulsant_RC0', 'Co_RX_PPI_RC0', 'Co_RX_H2Receptor_RC0', 'Co_RX_OthGastro_RC0',
        'Co_RX_ACE_RC0', 'Co_RX_ARB_RC0', 'Co_RX_BBlocker_RC0', 'Co_RX_CCB_RC0', 'Co_RX_Thiazide_RC0',
        'Co_RX_Loop_RC0', 'Co_RX_Potassium_RC0', 'Co_RX_Nitrates_RC0', 'Co_RX_Aliskiren_RC0',
        'Co_RX_OthAntihypertensive_RC0', 'Co_RX_Antiarrhythmic_RC0', 'Co_RX_OthAnticoagulant_RC0',
        'Co_RX_Insulin_RC0', 'Co_RX_Noninsulin_RC0', 'Co_RX_Digoxin_RC0', 'Co_RX_Statin_RC0',
        'Co_RX_Lipid_RC0', 'Co_RX_Lithium_RC0', 'Co_RX_Benzo_RC0', 'Co_RX_ZDrugs_RC0',
        'Co_RX_OthAnxiolytic_RC0', 'Co_RX_Dementia_RC0', 'Co_RX_Hormone_RC0',
        'Co_RX_Osteoporosis_RC0', 'Co_N_Drugs_RC0', 'Co_N_Hosp_RC0', 'Co_Total_HospLOS_RC0',
        'Co_N_MDVisit_RC0', 'Co_RX_AnyAspirin_RC0', 'Co_RX_AspirinMono_RC0', 'Co_RX_ClopidogrelMono_RC0',
        'Co_RX_AspirinClopidogrel_RC0', 'Co_RX_DM_RC0', 'Co_RX_Antipsychotic_RC0'
]

co_train_gpop = train_set[predictor_variable]
co_train_high = train_set_high[predictor_variable]
co_train_low = train_set_low[predictor_variable]

co_validation_gpop = validation_set[predictor_variable]
co_validation_high = validation_set_high[predictor_variable]
co_validation_low = validation_set_low[predictor_variable]
len(predictor_variable)



125

In [11]:
out_train_death_gpop = train_set['ehr_claims_death']
out_train_death_high = train_set_high['ehr_claims_death']
out_train_death_low = train_set_low['ehr_claims_death']

out_validation_death_gpop = validation_set['ehr_claims_death']
out_validation_death_high = validation_set_high['ehr_claims_death']
out_validation_death_low = validation_set_low['ehr_claims_death']

In [12]:
def bart(X_train, y_train):
    from bartpy.sklearnmodel import SklearnModel
    from sklearn.model_selection import GridSearchCV
    from bartpy.data import Data
    from bartpy.sigma import Sigma
    param_grid = [{
        'n_trees': [10,30,50] #
    }]
    model = SklearnModel()
    clf = GridSearchCV(estimator = model, param_grid = param_grid, n_jobs = 10, verbose = True)
    best_clf = clf.fit(X_train, y_train.to_numpy())
    print(best_clf)
    return best_clf 

In [13]:
def scores(X_train,y_train, best_clf):
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import f1_score
    from sklearn.metrics import fbeta_score
    from sklearn.metrics import roc_auc_score 
    from sklearn.metrics import log_loss
    import numpy as np
    pred = np.round(best_clf.predict(X_train))
    print(pred)
    actual = y_train
    print(accuracy_score(actual,pred))
    print(f1_score(actual,pred))
    print(fbeta_score(actual,pred, average = 'macro', beta = 2))
    print(roc_auc_score(actual, best_clf.predict(X_train)))
    print(log_loss(actual,best_clf.predict(X_train)))

In [14]:
def cross_val(X,y):
    from sklearn.model_selection import KFold
    from sklearn.model_selection import cross_validate
    from sklearn.metrics import log_loss
    from sklearn.metrics import roc_auc_score
    from sklearn.metrics import fbeta_score
    import sklearn
    import numpy as np
    cv = KFold(n_splits=5, random_state=1, shuffle=True)
    log_loss = [] 
    auc = [] 
    accuracy = []
    f1 = []
    f2 = [] 
    for train_index, test_index in cv.split(X):
        X_train, X_test, y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
        model = bart(X_train, y_train)
        prob = model.predict(X_test) # prob is a vector of probabilities 
        pred = np.round(model.predict(X_test)) # pred is the rounded predictions 
        log_loss.append(sklearn.metrics.log_loss(y_test, prob))
        auc.append(sklearn.metrics.roc_auc_score(y_test, prob))
        accuracy.append(sklearn.metrics.accuracy_score(y_test, pred))
        f1.append(sklearn.metrics.f1_score(y_test, pred, average = 'macro'))
        f2.append(fbeta_score(y_test,pred, average = 'macro', beta = 2))
    print(np.mean(accuracy))
    print(np.mean(f1))
    print(np.mean(f2))
    print(np.mean(auc))
    print(np.mean(log_loss))

In [15]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_gpop_sm,out_train_death_gpop_sm = sm.fit_resample(co_train_gpop,out_train_death_gpop)

best_clf = bart(co_train_gpop_sm,out_train_death_gpop_sm)

cross_val(co_train_gpop_sm,out_train_death_gpop_sm)

print()

scores(co_train_gpop, out_train_death_gpop, best_clf)

print() 

scores(co_validation_gpop,out_validation_death_gpop, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [0.01175388        nan 0.16642552]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.01138059         nan  0.1620341 ]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [0.02402406 0.13524671        nan]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.13598931 0.15761603]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.9379729498373566
0.9378228115239832
0.9373860622346728
0.980900183287925
0.22558757753846764



TypeError: scores() missing 1 required positional argument: 'best_clf'

In [16]:
scores(co_train_gpop, out_train_death_gpop, best_clf)

print() 

scores(co_validation_gpop,out_validation_death_gpop, best_clf)

[0. 0. 0. ... 0. 0. 0.]
0.9093448372179634
0.17972479640550407
0.551338674137878
0.8373725453065021
0.2842284361713935

[0. 0. 0. ... 0. 0. 0.]
0.8980853609892302
0.15953947368421054
0.5422010784127999
0.8246557979875679
0.31058521191160965


In [9]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_low_sm,out_train_death_low_sm = sm.fit_resample(co_train_low,out_train_death_low)

best_clf = bart(co_train_low_sm,out_train_death_low_sm)

cross_val(co_train_low_sm,out_train_death_low_sm)

print()

scores(co_train_low, out_train_death_low, best_clf)

print() 

scores(co_validation_low,out_validation_death_low, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.12853905 0.14334549]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.11882162 0.13354214]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.12444816 0.14021882]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [0.05070436        nan 0.13960879]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.9194556822361161
0.9191996498797244
0.9187123772382908
0.9729928322493837
0.27386192423084404

[0. 0. 0. ... 0. 0. 0.]
0.8841948631687908
0.3255463451394122
0.6102844142029223
0.8371551942431606
0.3380479924502778

[ 0.  0. -0. ...  0.  0.  1.]
0.86438251574728
0.28196058615462355
0.587555793444083
0.8060882262092665
0.373981566085589
1:08:24.992987


In [9]:
import datetime
begin_time = datetime.datetime.now()

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 42)
co_train_high_sm,out_train_death_high_sm = sm.fit_resample(co_train_high,out_train_death_high)

best_clf = bart(co_train_high_sm,out_train_death_high_sm)

cross_val(co_train_high_sm,out_train_death_high_sm)

print()

scores(co_train_high, out_train_death_high, best_clf)

print() 

scores(co_validation_high,out_validation_death_high, best_clf)


print(datetime.datetime.now() - begin_time)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.06126924         nan  0.11287813]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/PHShome/se197/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.10890276]
  warnings.warn(


GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
Fitting 5 folds for each of 3 candidates, totalling 15 fits
GridSearchCV(estimator=SklearnModel(), n_jobs=10,
             param_grid=[{'n_trees': [10, 30, 50]}], verbose=True)
0.9545803971812941
0.9544926953709798
0.9541698283035395
0.9865495593307502
0.20471477570784868

[-0.  0.  0. ...  0.  0.  0.]
0.9311620138391792
0.1244309559939302
0.5340307539850592
0.8434033309758999
0.2393684193093201

[0. 0. 0. ... 0. 0. 0.]
0.9290039674253497
0.12144702842377263
0.5328243569355763
0.8261646408527018
0.24254771046454277
1:26:51.008614
